package deti.tqs.fbarros.airqualityapp;

// Generated by Selenium IDE
import io.github.bonigarcia.seljup.SeleniumJupiter;
import org.junit.jupiter.api.Test;

import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.By;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;


@ExtendWith(SeleniumJupiter.class)
class ValidCityAQI_SeleniumIDE {

    ChromeDriver driver;

    public ValidCityAQI_SeleniumIDE(ChromeDriver driver) {
      this.driver = driver;
    }


    @Test
    void validCityAQI() {
        driver.get("http://127.0.01:8080");
        driver.manage().window().setSize(new Dimension(2560, 1004));

        assertThat(driver.getTitle(), is("TQS Air Quality App"));
        {
            WebElement element = driver.findElement(By.cssSelector("h2"));
            String text = element.getText();
            assertThat(text, is("Welcome to the Air Quality Application!"));
        }
        {
            WebElement element = driver.findElement(By.cssSelector("h3"));
            String text = element.getText();
            assertThat(text, is("Input the name of the city:"));
        }
        {
            WebElement element = driver.findElement(By.cssSelector(".p-3"));
            String text = element.getText();
            assertThat(text, is("© 2021 Copyright: Francisca Barros"));
        }

        driver.findElement(By.id("city_input")).click();
        driver.findElement(By.id("city_input")).sendKeys("berlin");

        {
            WebElement element = driver.findElement(By.cssSelector(".btn"));
            String text = element.getText();
            assertThat(text, is("Check City AQI!"));
        }

        driver.findElement(By.cssSelector(".btn")).click();

        {
            WebElement element = driver.findElement(By.cssSelector("h2"));
            String text = element.getText();
            assertThat(text, is("Showing results for: BERLIN"));
        }
        {
            WebElement element = driver.findElement(By.cssSelector("th:nth-child(6)"));
            String text = element.getText();
            assertThat(text, is("PM10"));
        }

    }
}
